Feature/improve test coverage
eXolnet/laravel-bento pull request #35
Opened 2021-01-22 20:24 UTC by ChristopheTremblay

Test coverage was improved to 100% files/98% lines

2021-04-07 21:36 UTC, xel1045 requested changes
J'ai effectué un tour des tests et je trouve ça très bon. Par contre, il y a quelques éléments de styles qui devraient être corrigés.

2021-04-07 21:36 UTC, xel1045 commented on tests/Integration/BentoServiceProviderTest.php
> + */
Ce commentaire devrait être enlevé. C'est la seule classe qui en a un.

2021-04-07 21:36 UTC, xel1045 commented on tests/Integration/BentoServiceProviderTest.php
> +        $this->app->alias('blade.compiler', Illuminate\View\Compilers\BladeCompiler::class);
Je ne comprends pas pourquoi tu as besoin de créer un `alias` dans le `setUp` du test. C'est la première fois que je vois ça. Est-ce nécessaire?

2021-04-07 21:36 UTC, xel1045 commented on tests/Integration/BentoServiceProviderTest.php
> +     * https://stevegrunwell.com/blog/custom-laravel-blade-directives/
```suggestion
     *
     * @see https://stevegrunwell.com/blog/custom-laravel-blade-directives/
```

2021-04-07 21:36 UTC, xel1045 commented on tests/Integration/BentoServiceProviderTest.php
> +     * https://stevegrunwell.com/blog/custom-laravel-blade-directives/
C'est très cool comme façon de tester les directives. Belle trouvaille!

2021-04-07 21:36 UTC, xel1045 commented on tests/Integration/BentoTest.php
> +     * @return void
```suggestion
     * @return void
     * @test
```

2021-04-07 21:36 UTC, xel1045 commented on tests/Integration/BentoTest.php
> +     * @return void
```suggestion
     * @return void
     * @test
```

2021-04-07 21:36 UTC, xel1045 commented on tests/Integration/BentoTest.php
> +     * @return void
```suggestion
     * @return void
     * @test
```

2021-04-07 21:36 UTC, xel1045 commented on tests/Integration/FeatureCreationTest.php
> +     * @return void
```suggestion
     * @return void
     * @test
```

2021-04-07 21:36 UTC, xel1045 commented on tests/Integration/FeatureCreationTest.php
> +    public function testCreateNewFeatureWithDefaultParam():void
```suggestion
    public function testCreateNewFeatureWithDefaultParam(): void
```

2021-04-07 21:36 UTC, xel1045 commented on tests/Integration/FeatureCreationTest.php
> +     * @return void
```suggestion
     * @return void
     * @test
```

2021-04-07 21:36 UTC, xel1045 commented on tests/Integration/FeatureCreationTest.php
> +    public function testCreateNewFeatureWithInjection():void
```suggestion
    public function testCreateNewFeatureWithInjection(): void
```

2021-04-07 21:36 UTC, xel1045 commented on tests/Integration/FeatureCreationTest.php
> +     * @return void
```suggestion
     * @return void
     * @test
```

2021-04-07 21:36 UTC, xel1045 commented on tests/Integration/FeatureCreationTest.php
> +    public function testCreateNewFeatureWithParameterAlreadyInParamters():void
```suggestion
    public function testCreateNewFeatureWithParameterAlreadyInParamters(): void
```

2021-04-07 21:36 UTC, xel1045 commented on tests/Unit/Strategy/DateTest.php
> +
```suggestion
```

2021-04-07 21:36 UTC, xel1045 commented on tests/Unit/Strategy/EnvironmentTest.php
> +
```suggestion
```

2021-04-07 21:36 UTC, xel1045 commented on tests/Unit/Strategy/EnvironmentTest.php
> +
```suggestion
```

2021-04-07 21:36 UTC, xel1045 commented on tests/Unit/Strategy/EnvironmentTest.php
> +    /**
```suggestion

    /**
```

2021-04-07 21:36 UTC, xel1045 commented on tests/Unit/Strategy/HostnameTest.php
> +
```suggestion
```

2021-04-07 21:36 UTC, xel1045 commented on tests/Unit/Strategy/HostnameTest.php
> +
```suggestion
```

2021-04-07 21:36 UTC, xel1045 commented on tests/Integration/BentoServiceProviderTest.php
> +
```suggestion
```

2021-04-07 21:36 UTC, xel1045 commented on tests/Integration/BentoServiceProviderTest.php
> +
```suggestion
```

2021-04-07 21:36 UTC, xel1045 commented on tests/Unit/Strategy/HostnameTest.php
> +        parent::setUp(); // TODO: Change the autogenerated stub
Est-ce normal que tu as laissé un TODO ici?

2021-04-07 21:36 UTC, xel1045 commented on tests/Unit/Strategy/LogicNotTest.php
> +
```suggestion
```

2021-04-07 21:36 UTC, xel1045 commented on tests/Unit/Strategy/LogicNotTest.php
> +    protected function setUp(): void
```suggestion
    /**
     * @return void
     */
    protected function setUp(): void
```

2021-04-07 21:36 UTC, xel1045 commented on tests/Unit/Strategy/LogicNotTest.php
> +        $this->feature = \Mockery::mock(Feature::class);
La classe `Mockery` devrait être importée.

2021-04-07 21:36 UTC, xel1045 commented on tests/Unit/Strategy/LogicNotTest.php
> +        parent::setUp(); // TODO: Change the autogenerated stub
Est-ce normal que tu as laissé un TODO ici?

2021-04-07 21:36 UTC, xel1045 commented on tests/Unit/Strategy/StrategyContainerTest.php
> +
```suggestion
```

2021-04-07 21:36 UTC, xel1045 commented on tests/Unit/Strategy/StrategyContainerTest.php
> +     * @var Exolnet\Bento\Bento
Tu dois mettre le backslash devant Exolnet, sinon c'est comme si tu référençait la classe `Exolnet\Bento\Tests\Unit\Strategy\Exolnet\Bento\Bento`

```suggestion
     * @var \Exolnet\Bento\Bento
```

2021-04-07 21:36 UTC, xel1045 commented on tests/Unit/Strategy/StrategyContainerTest.php
> +     * @var Exolnet\Bento\Feature
```suggestion
     * @var \Exolnet\Bento\Feature
```

2021-04-07 21:36 UTC, xel1045 commented on tests/Unit/Strategy/StrategyContainerTest.php
> +     * @var Exolnet\Bento\Strategy\LogicAnd
```suggestion
     * @var \Exolnet\Bento\Strategy\LogicAnd
```

2021-04-07 21:36 UTC, xel1045 commented on tests/Unit/Strategy/StrategyContainerTest.php
> +        parent::setUp(); // TODO: Change the autogenerated stub
Est-ce normal que tu as laissé un TODO ici?

2021-04-07 21:36 UTC, xel1045 commented on tests/Unit/Strategy/VisitorPercentTest.php
> +    protected function setUp(): void
```suggestion
    /**
     * @return void
     */
    protected function setUp(): void
```

2021-04-07 21:36 UTC, xel1045 commented on tests/Unit/Strategy/VisitorPercentTest.php
> +    protected $visitorPercent;
Il manque la phpDoc sur ces trois variables.

2021-04-07 21:36 UTC, xel1045 commented on tests/Unit/Strategy/VisitorPercentTest.php
> +        parent::setUp(); // TODO: Change the autogenerated stub
Est-ce normal que tu as laissé un TODO ici?

2021-04-07 21:36 UTC, xel1045 commented on tests/Unit/Strategy/VisitorPercentTest.php
> +        $this->feature = \Mockery::mock(Feature::class);
La classe `Mockery` devrait être importée.

2021-04-07 21:36 UTC, xel1045 commented on tests/Unit/Strategy/VisitorPercentTest.php
> +    public function testGetPercent(): void
```suggestion
    /**
     * @return void
     */
    public function testGetPercent(): void
```

2021-04-07 21:36 UTC, xel1045 commented on tests/Unit/Strategy/VisitorPercentTest.php
> +    public function testGetPercent(): void
```suggestion
    /**
     * @return void
     * @test
     */
    public function testGetPercent(): void
```

2021-06-17 20:23 UTC, ChristopheTremblay commented
J'ai fait toutes les corrections de style et php docs demandés. 

J'ai aussi review l'utilisation de l'alias dans la méthode `setUp()` de `BentoTest.php`. Je ne me rappelle pas vraiment de la raison pour laquelle j'ai pensé devoir l'utiliser. Je suis tombé sur certains commentaires Github mentionnant que BladeCompiler n'était pas reconnu de base par Laravel et il fallait donc créer un alias manuellement. Toutefois c'était sur Laravel 5.7. Je n'arrive plus à retrouver ce thread malheureusement. 

Mais bon, j'ai tsté sans le alias et tous les tests sont passés. Je l'ai donc supprimé

2021-07-09 15:55 UTC, xel1045 approved these changes

2021-07-09 15:57 UTC, merged